### ISSUE TITLE
Feature Request: Parameters to set the target resolution of the images

### ISSUE THREAD

**Issue by dandubya** [wearemothership/react-fast-scroll-pdf#32]
I have a use case where I'd like to control the resolution of the images produced. By default, they are fairly low resolution, especially when viewed on a 4K or Retina display. I'd like to sometimes make the images higher resolution by setting the DPI.

Ideally, I could set the max width and/or max height of the image in the viewport, and independently control the resolution (DPI).

Thanks for considering.

**Comment by vespasianvs** [comment]
Hey, that's a great idea. It may be a little time before I get to it though I'm afraid as I have some other projects on the go at the moment. Have you tried v1.3.0? The way that the page images are rendered was changed and we have seen a massive improvement on the quality of the PDF display in out own tests.

**Comment by dandubya** [comment]
I tried upgrading to v1.3.0 today and somehow borked my whole dev environment. Going to keep trying.

**Comment by dandubya** [comment]
Upgrading to 1.2.1 and to 1.3.0 has solved the low-resolution problems, so I'm going to close this feature request.
